//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WMI.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_WMITYPE                     129
#define IDD_PROCUR_CHILDTEXT            132
#define IDD_DISTRIBUT_CHILDTEXT         156
#define IDD_WAREHOUSE_CHILDTEXT         157
#define IDD_MANAGE_CHILDTEXT            158
#define IDD_DATA_CHILDTEXT              159
#define IDD_ASSETS_CHILDTEXT            160
#define IDD_SET_CHILDTEXT               161
#define IDD_TITLE_CHILDTEXT             162
#define IDD_LOG                         167
#define IDD_EXTERN_PARENT               168
#define IDB_LOGO_BLAK                   169
#define IDR_MENU                        175
#define IDD_SET_SYS_PARAM               199
#define IDD_DIALOG_ADD                  203
#define IDD_TABDLG                      204
#define IDB_ADD                         207
#define IDB_DEL                         208
#define IDB_LOGO_GREEN                  211
#define IDB_BITMAP1                     212
#define IDR_DELETE                      213
#define IDD_CHANGEPASS                  219
#define IDB_HOME                        220
#define IDD_ADD_ORDER                   222
#define IDD_ADD_DISTRI                  223
#define IDD_ADD_WAREIN                  224
#define IDD_ADD_OTHERIN                 226
#define IDD_ADD_RECV                    227
#define IDD_ADD_WARE_ADJ                229
#define IDD_ADD_WAREOUT                 230
#define IDD_ADD_OTHEROUT                231
#define IDD_ADD_PAY                     232
#define IDD_ADD_CHARAC                  233
#define IDD_ADD_GOODS                   234
#define IDD_ADD_DISTRI_RETURN           235
#define IDD_ADD_ORDER_RETURN            236
#define IDC_DELETE                      1004
#define IDC_EDIT1                       1006
#define IDC_EDIT2                       1007
#define IDC_EDIT3                       1008
#define IDC_COMBO1                      1009
#define IDC_EDIT4                       1009
#define IDC_COMBO2                      1010
#define IDC_NAME                        1010
#define IDC_COMBO3                      1011
#define IDC_Contacts                    1011
#define IDC_ADD                         1014
#define IDC_ChangePass                  1025
#define IDC_PERSON_LOG                  1026
#define IDC_ODER                        1026
#define IDC_LOGOUT                      1027
#define IDC_TRACKING                    1028
#define IDC_RETURN                      1029
#define IDC_DISTRIBUT                   1031
#define IDC_TACKING                     1033
#define IDC_GODOWNENTRY                 1034
#define IDC_CUSMANAGE                   1035
#define IDC_EXITLS                      1036
#define IDC_SUPPLYMANAGE                1036
#define IDC_STOCKING                    1037
#define IDC_GODSMANAGE                  1037
#define IDC_WAREHOUSEMANAGE             1038
#define IDC_ADJUSTMENT                  1039
#define IDC_Employ                      1039
#define IDC_VOUCHER                     1040
#define IDC_PAYMENT                     1041
#define IDC_OTHERINCOME                 1043
#define IDC_EXPENDITURE                 1044
#define IDC_Payable                     1045
#define IDC_EXPENSE                     1046
#define IDC_Recvable                    1046
#define IDC_SCHEDULEPAY                 1047
#define IDC_SCHEDULERECEIVE             1048
#define IDC_CUSSTATEMENT                1049
#define IDC_VENDORSTATMENT              1050
#define IDC_INCOMESTATEMENT             1051
#define IDC_SYSSET                      1052
#define IDC_INCOME                      1052
#define IDC_OPERATLOG                   1054
#define IDC_LIST1                       1062
#define IDC_BUTTON1                     1063
#define IDC_BUTTON2                     1064
#define IDC_TAB1                        1067
#define IDC_OK                          1068
#define IDC_COMBO4                      1070
#define IDC_COMBO6                      1071
#define IDC_PARAM                       1080
#define IDC_STATIC1                     1086
#define IDC_LIST2                       1089
#define IDC_PHONE                       1091
#define IDC_COUNT                       1092
#define IDC_ADDRESS                     1093
#define IDC_STATIC_NAME                 1094
#define IDC_OPT                         1095
#define IDC_STATIC_CONTAC               1096
#define IDC_GOODNAME                    1098
#define IDC_MIN                         1100
#define IDC_TEXT                        1101
#define IDC_PRICE                       1106
#define IDR_TAB_CLOSE_THIS              32774
#define IDR_TAB_CLOSE_OTHER             32775
#define IDR_TAB_CLOSE_ALL               32776
#define IDR_TAB_REFREASH                32777
#define IDM_DELETE                      32778
#define IDM_CANCEL                      32779
#define IDS_ED                          61220
#define IDS_LS                          61221
#define IDS_LS2                         61222
#define IDS_CB                          61223
#define IDS_CB2                         61224
#define IDS_CB3                         61225
#define IDS_CB4                         61226
#define IDS_BT                          61227
#define IDS_BT2                         61228
#define IDS_BT3                         61229
#define IDS_BT4                         61230
#define IDS_BT5                         61231
#define IDS_BT6                         61232
#define IDS_TM                          61233
#define IDS_TM2                         61234
#define IDS_ADD_ED                      61235
#define IDS_TREE                        61236
#define IDS_PIC_ADD                     61237
#define IDS_PIC_DEL                     61238
#define IDC_CLIST                       61239
#define IDC_LOG                         61240
#define IDC_ID                          61241
#define IDC_PASSWORD                    61242

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        238
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1107
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
